<?php
// This file is automatically generated
$bt_settings['type'] = 'exec';
$bt_settings['pages'] = 'checked';
$bt_settings['revisions'] = 'checked';
$bt_settings['subscriptions'] = 'checked';
$bt_settings['media'] = 'checked';
$bt_settings['config'] = 'checked';
$bt_settings['templates'] = 'checked';
$bt_settings['plugins'] = 'checked';
