<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: moritz
 * Date: Sat, 05 Mar 2011 09:00:32 +0100
 */

$conf['title'] = 'Wiki';
$conf['start'] = 'index';
$conf['template'] = 'torservers';
$conf['license'] = 'publicdomain';
$conf['breadcrumbs'] = 0;
$conf['youarehere'] = 1;
$conf['refcheck'] = 0;
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['registernotify'] = 'admin@torservers.net';
$conf['notify'] = 'internal@torservers.net';
$conf['subscribers'] = 1;
$conf['userewrite'] = '1';
$conf['useslash'] = 1;
$conf['mailfrom'] = 'wiki@www.torservers.net';
$conf['rss_content'] = 'htmldiff';
$conf['renderer_xhtml'] = 'highlightjs';
$conf['plugin']['maintenancemessage']['maintenance_message_text'] = 'We are currently migrating servers.';
$conf['plugin']['maintenancemessage']['deny_editing_message'] = 'Editing pages has been disabled for the maintenance period. Please check back once the maintenance is complete.';
$conf['plugin']['editsections']['cache'] = 'disabled';
$conf['plugin']['editsections']['order_type'] = 'nested';
$conf['tpl']['torservers']['font-size'] = '1.0em';
$conf['tpl']['torservers']['hide-entry-title'] = 1;

// end auto-generated content
